language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - cd memcached_operator
  - pip install pipenv
  - pipenv install --dev
# command to run tests
script:
  - pipenv run nosetests
